name: JSON Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jsonlint-cli
        run: npm install -g jsonlint-cli

      - name: Validate JSON file
        run: jsonlint -q data.json


