name: JSON Validation

on:
  push:
    branches: [ main ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install ajv-cli
      run: npm install -g ajv-cli

    - name: Validate JSON
      run: ajv compile -s schema.json -d data.json
