name: JSON Validation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  json-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Validate JSON
      run: |
        curl -s https://api.github.com/repos/signalhub/api-fetch-data/contents/data.json | jsonlint
