name: JSON Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate JSON
        run: ajv validate -s ./schema.json -d ./data.json
